import 'package:flutter/material.dart';
import 'package:new_dhc/dropdown_editing_controller.dart';

class UserPSS {
  late DropDownEditingController actualPathologies;
  late DropDownEditingController adi;
  late DropDownEditingController adp;
  late TextEditingController adverseReactions;
  late TextEditingController aids;
  late DropDownEditingController bloodGroup;
  late DropDownEditingController rhFactor;
  late TextEditingController bloodPressure;
  late TextEditingController bmi;
  late DropDownEditingController chronicPathologies;
  late TextEditingController chronicPharmacologicalTherapies;
  late TextEditingController mmgCf;
  late TextEditingController mmgBirthDate;
  late TextEditingController mmgEmail;
  late TextEditingController mmgFirstName;
  late TextEditingController height;
  late TextEditingController mmgLastName;
  late TextEditingController medicalHistory;
  late TextEditingController missingOrgans;
  late TextEditingController motorSkills;
  late TextEditingController organDonation;
  late TextEditingController othersPharmacologicalTherapies;
  late TextEditingController mmgPec;
  late TextEditingController mmgPhone;
  late TextEditingController pregnancies;
  late TextEditingController prosthetics;
  late TextEditingController relevantMalformations;
  late TextEditingController riskFactors;
  late TextEditingController skinAllergies;
  late TextEditingController transplants;
  late TextEditingController vaccinations;
  late TextEditingController venomAllergies;
  late TextEditingController weight;
  late TextEditingController workingActivity;
  late TextEditingController familyHealthHistory;
  late TextEditingController atsCode;
  late TextEditingController exemptionCodes;
  late TextEditingController userArea;
  late TextEditingController pathologyNetworks;
  late TextEditingController associations;
  late DropDownEditingController livesAlone;

  UserPSS() {
    actualPathologies = DropDownEditingController();
    adi = DropDownEditingController();
    adp = DropDownEditingController();
    adverseReactions = TextEditingController();
    aids = TextEditingController();
    bloodGroup = DropDownEditingController();
    rhFactor = DropDownEditingController();
    bloodPressure = TextEditingController();
    bmi = TextEditingController();
    chronicPathologies = DropDownEditingController();
    chronicPharmacologicalTherapies = TextEditingController();
    othersPharmacologicalTherapies = TextEditingController();
    mmgCf = TextEditingController();
    mmgBirthDate = TextEditingController();
    mmgEmail = TextEditingController();
    mmgFirstName = TextEditingController();
    mmgLastName = TextEditingController();
    medicalHistory = TextEditingController();
    mmgPec = TextEditingController();
    mmgPhone = TextEditingController();
    pregnancies = TextEditingController();
    prosthetics = TextEditingController();
    relevantMalformations = TextEditingController();
    riskFactors = TextEditingController();
    skinAllergies = TextEditingController();
    transplants = TextEditingController();
    vaccinations = TextEditingController();
    venomAllergies = TextEditingController();
    weight = TextEditingController();
    height = TextEditingController();
    missingOrgans = TextEditingController();
    organDonation = TextEditingController();
    motorSkills = TextEditingController();
    workingActivity = TextEditingController();
    familyHealthHistory = TextEditingController();
    atsCode = TextEditingController();
    exemptionCodes = TextEditingController();
    userArea = TextEditingController();
    pathologyNetworks = TextEditingController();
    associations = TextEditingController();
    livesAlone = DropDownEditingController();
  }

  dispose() {
    adverseReactions.dispose();
    aids.dispose();
    bloodPressure.dispose();
    bmi.dispose();
    chronicPharmacologicalTherapies.dispose();
    othersPharmacologicalTherapies.dispose();
    mmgCf.dispose();
    mmgBirthDate.dispose();
    mmgEmail.dispose();
    mmgFirstName.dispose();
    mmgLastName.dispose();
    medicalHistory.dispose();
    mmgPec.dispose();
    mmgPhone.dispose();
    pregnancies.dispose();
    prosthetics.dispose();
    relevantMalformations.dispose();
    riskFactors.dispose();
    skinAllergies.dispose();
    transplants.dispose();
    vaccinations.dispose();
    venomAllergies.dispose();
    weight.dispose();
    height.dispose();
    missingOrgans.dispose();
    organDonation.dispose();
    motorSkills.dispose();
    workingActivity.dispose();
    familyHealthHistory.dispose();
    atsCode.dispose();
    exemptionCodes.dispose();
    userArea.dispose();
    pathologyNetworks.dispose();
    associations.dispose();
  }
}
